### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by miguelmota** [miguelmota/global-keypress#1]
- [ ] CLI, ie `gk start`, `gk start -d` (daemon), `gk stop`, `gk -o events.log`
- [x] linux support
- [ ] windows support
- [x] check for daemon, reuse out stream

**Comment by albinekb** [comment]
Really cool project! 🎉 

- Add support for https://developer.apple.com/reference/coregraphics/cgeventflags?language=objc   (modifier keys) `kCGEventFlagsChanged`
?

**Comment by miguelmota** [comment]
@albinekb good feature request. will look in to it. thanks!

**Comment by albinekb** [comment]
Tested with this:
added `kCGEventFlagsChanged` to the eventMask
```c
  if (type == kCGEventFlagsChanged) {
    CGEventFlags eventFlags = CGEventGetFlags(event);
    bool shift = (eventFlags & kCGEventFlagMaskShift) == kCGEventFlagMaskShift;
    if (shift) {
      printf("%d\n", 65);
      fflush(stdout);
    }
    return event;
  }
```

(first time programming in C 😄  
I'll look into if i can make it work cleanly, and maybe send a PR :)

**Comment by miguelmota** [comment]
@albinekb modifier key support added for macOS

Thanks!

**Comment by kolnogorov** [comment]
It's really a great project!
Any news on Windows support?

**Comment by miguelmota** [comment]
@kolnogorov I don't have a windows machine but happy to merge a PR
